name: Buildando .NET, frontend e subindo no Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-vite:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Web/farfarawaypetcare-react
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup do Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Instalando dependências
        uses: bahmutov/npm-install@v1

      - name: Buildando
        run: npm run build

      - name: Upload dos production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  build-dotnet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API/Application
    steps:
      - uses: actions/checkout@v2

      - name: Configurando .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.401"
          include-prerelease: true

      - name: Buildando
        run: dotnet build --configuration Production

      - name: dotnet publish
        run: dotnet publish -c Production -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload do artefato para deploy
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build-dotnet
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download do artefato do build
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      
      - name: Download do artefato do build-vite
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./wwwroot

      - name: Deploy no Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "farfarawaypetcare-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d94ee2b341f4524a87f3c350436029f }}
          package: .